#!/bin/sh
if [ "$1" = "-s" ]; then
    while IFS="= " read var restofline; do
    echo "$0 $(date) $var=$restofline" >> /data/fw.log
    case "$var" in
        mender_boot_part)
            part="$restofline"
            slot=
            tegra-boot-control --set-active $slot
            ;;
        upgrade_available)
            if [ "$restofline" = "1" ]; then
                touch /var/lib/mender/upgrade_available
            else
                rm -f /var/lib/mender/upgrade_available
            fi
           ;;
        *)
           echo "ERR: no such variable: $1" >&2
           exit 1
    esac
    done
fi
exit 0
